name: cicd

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - docs/**
      - mkdocs.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.setid.outputs.commit_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Shorten commit id
        id: setid
        run: echo "commit_id=${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            roegema/python-app:${{ steps.setid.outputs.commit_id }}
            roegema/python-app:latest

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Modify values file
        run: |
          yq -i '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/python-app/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update values.yaml with commit ${{ needs.ci.outputs.commit_id }}"
          add: "charts/python-app/values.yaml"

      - name: ArgoCD app sync
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}

          argocd app sync python-app

  techdocs:
    name: Build and publish TechDocs
    runs-on: ubuntu-latest
    needs: cd

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install TechDocs requirements
        run: |
          pip install mkdocs mkdocs-techdocs-core

      - name: Build TechDocs
        run: mkdocs build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
